

#ifndef CONFIG_H
#define CONFIG_H

#define ASSEMBLY_FILE_EXTENSION ".as"

#define MEMORY_CAPACITY 256

#define MEMORY_ADDRESS_OFFSET 100

#define MEMORY_AVAILABLE_SPACE (MEMORY_CAPACITY - MEMORY_ADDRESS_OFFSET)

#define EXTERNAL_TEMP_ADDR 0

#define NAME_MAX_LEN 30

#define FILE_NAME_MAX_LEN 30

#define MAX_LINE_LEN 80

#define INSTRUCTIONS_AMOUNT 16
#define DIRECTIVES_AMOUNT 3
#define REGISTERS_AMOUNT 8
#define ATTRIBUTE_DIRECTIVES_AMOUNT 2
#define MACRO_DECLARATION_WORDS 2

#define MAX_NUM_DIGITS 15

#define mat_size  (row * col)

#define MAX_ENCODED_WORDS_PER_INSTRUCTION  5

#define ONE_BIT_MASK  0x1
#define WORD_BIT_SIZE  10
#define WORD_BIT_MASK ((1U << WORD_BIT_SIZE) - 1)
#define WORD_MAX_NUM  ((1 << (WORD_BIT_SIZE - 1)) - 1)
#define WORD_MIN_NUM  (-(1 << (WORD_BIT_SIZE - 1)))

#define OPERAND_DATA_BITS 8 /*MSB*/
#define OPERAND_DATA_BITS_SHIFT (WORD_BIT_SIZE - OPERAND_DATA_BITS) /* its MSB, the shift depends on word bit size*/
#define OPERAND_DATA_BITS_MASK ~((1U << OPERAND_DATA_BITS_SHIFT) - 1)

#define OPERAND_DATA_DEST_REG_BITS (OPERAND_DATA_BITS/2)
#define OPERAND_DATA_DEST_REG_SHIFT 2
#define OPERAND_DATA_DEST_REG_MASK ((1U << OPERAND_DATA_DEST_REG_BITS) - 1) << OPERAND_DATA_DEST_REG_SHIFT

#define OPERAND_DATA_SRC_REG_BITS (OPERAND_DATA_BITS/2)
#define OPERAND_DATA_SRC_REG_SHIFT 6
#define OPERAND_DATA_SRC_REG_MASK ((1U << OPERAND_DATA_SRC_REG_BITS) - 1) << OPERAND_DATA_SRC_REG_SHIFT

#define OPCODE_BITS 4 /*MSB*/
#define OPCODE_BITS_SHIFT (WORD_BIT_SIZE - OPCODE_BITS)/* its MSB, the shift depends on word bit size*/
#define OPCODE_BITS_MASK ~((1U << OPCODE_BITS_SHIFT) - 1)

#define E_R_A_BITS 2
#define E_R_A_BITS_SHIFT 0
#define E_R_A_BITS_MASK ((1U << E_R_A_BITS) - 1) << E_R_A_BITS_SHIFT

#define SRC_ADDR_MODE_BITS 2
#define SRC_ADDR_MODE_BITS_SHIFT 4
#define SRC_ADDR_MODE_BITS_MASK ((1U << SRC_ADDR_MODE_BITS) - 1) << SRC_ADDR_MODE_BITS_SHIFT

#define DEST_ADDR_MODE_BITS 2
#define DEST_ADDR_MODE_BITS_SHIFT 2
#define DEST_ADDR_MODE_BITS_MASK ((1U << DEST_ADDR_MODE_BITS) - 1) << DEST_ADDR_MODE_BITS_SHIFT

#define MAX_NUM(m) ((1 << (m- 1)) - 1)
#define MIN_NUM(m) (-(1 << (m - 1)))

#define U_MAX_NUM(m) (1<< m) -1
#define U_MIN_NUM 0

#define OBJ_FILE_ADDRESS_PRINT_LENGTH 4

#define OBJ_FILE_DATA_PRINT_LENGTH 5


#endif
